cloud:
  aws:
    credentials:
      access-key: AKIA27Z7QKCM576GJWMJ
      secret-key: UGKk4oP2BXFrlKI2a6X43KUSd4dZmr7ZB/1rnAd8
    region:
      static: ap-south-1
    stack:
      auto: false

application:
  bucket:
    name: sampleimages-12


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

aws:
  s3:
    image:
      upload:
        url: https://sampleimages-12.s3.ap-south-1.amazonaws.com/

